[2024-05-12T02:39:47.208+0000] {processor.py:161} INFO - Started process (PID=169) to work on /opt/airflow/dags/blab.py
[2024-05-12T02:39:47.210+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T02:39:47.213+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:39:47.213+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T02:39:47.979+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:39:47.974+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 64, in <module>
    python_callable=extrect3
NameError: name 'extrect3' is not defined
[2024-05-12T02:39:47.981+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T02:39:48.000+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.801 seconds
[2024-05-12T02:40:18.311+0000] {processor.py:161} INFO - Started process (PID=181) to work on /opt/airflow/dags/blab.py
[2024-05-12T02:40:18.313+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T02:40:18.316+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:40:18.316+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T02:40:18.615+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:40:18.610+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 64, in <module>
    python_callable=extrect3
NameError: name 'extrect3' is not defined
[2024-05-12T02:40:18.617+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T02:40:18.632+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.337 seconds
[2024-05-12T02:40:48.828+0000] {processor.py:161} INFO - Started process (PID=193) to work on /opt/airflow/dags/blab.py
[2024-05-12T02:40:48.830+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T02:40:48.833+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:40:48.832+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T02:40:49.223+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:40:49.217+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 64, in <module>
    python_callable=extrect3
NameError: name 'extrect3' is not defined
[2024-05-12T02:40:49.225+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T02:40:49.253+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.433 seconds
[2024-05-12T02:41:19.495+0000] {processor.py:161} INFO - Started process (PID=205) to work on /opt/airflow/dags/blab.py
[2024-05-12T02:41:19.496+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T02:41:19.498+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:41:19.498+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T02:41:20.017+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:41:20.011+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 64, in <module>
    python_callable=extrect3
NameError: name 'extrect3' is not defined
[2024-05-12T02:41:20.019+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T02:41:20.039+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.552 seconds
[2024-05-12T02:41:50.159+0000] {processor.py:161} INFO - Started process (PID=217) to work on /opt/airflow/dags/blab.py
[2024-05-12T02:41:50.161+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T02:41:50.163+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:41:50.162+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T02:41:50.593+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:41:50.587+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 64, in <module>
    python_callable=extrect3
NameError: name 'extrect3' is not defined
[2024-05-12T02:41:50.595+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T02:41:50.614+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.461 seconds
[2024-05-12T02:41:59.306+0000] {processor.py:161} INFO - Started process (PID=223) to work on /opt/airflow/dags/blab.py
[2024-05-12T02:41:59.307+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T02:41:59.310+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:41:59.309+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T02:41:59.339+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:41:59.338+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5
    from airflow_providor.op
                            ^
SyntaxError: invalid syntax
[2024-05-12T02:41:59.340+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T02:41:59.361+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.065 seconds
[2024-05-12T02:42:29.490+0000] {processor.py:161} INFO - Started process (PID=235) to work on /opt/airflow/dags/blab.py
[2024-05-12T02:42:29.492+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T02:42:29.494+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:42:29.493+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T02:42:29.515+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:42:29.514+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5
    from airflow_providor.op
                            ^
SyntaxError: invalid syntax
[2024-05-12T02:42:29.516+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T02:42:29.541+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.059 seconds
[2024-05-12T02:42:36.606+0000] {processor.py:161} INFO - Started process (PID=246) to work on /opt/airflow/dags/blab.py
[2024-05-12T02:42:36.607+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T02:42:36.609+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:42:36.609+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T02:42:36.627+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:42:36.626+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5
    from airflow_providor.operoter impoer fivetranO
                                   ^
SyntaxError: invalid syntax
[2024-05-12T02:42:36.628+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T02:42:36.646+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.046 seconds
[2024-05-12T02:42:53.744+0000] {processor.py:161} INFO - Started process (PID=251) to work on /opt/airflow/dags/blab.py
[2024-05-12T02:42:53.745+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T02:42:53.748+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:42:53.747+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T02:42:53.763+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:42:53.762+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5
    from airflow_providor.operoter impoer fivetranOperator
                                   ^
SyntaxError: invalid syntax
[2024-05-12T02:42:53.764+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T02:42:53.784+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.048 seconds
[2024-05-12T02:43:00.838+0000] {processor.py:161} INFO - Started process (PID=262) to work on /opt/airflow/dags/blab.py
[2024-05-12T02:43:00.839+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T02:43:00.841+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:43:00.841+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T02:43:00.861+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:43:00.860+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5
    from airflow_providor.operoter impoer fivetranOperatorAs
                                   ^
SyntaxError: invalid syntax
[2024-05-12T02:43:00.861+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T02:43:00.881+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.052 seconds
[2024-05-12T02:43:06.906+0000] {processor.py:161} INFO - Started process (PID=267) to work on /opt/airflow/dags/blab.py
[2024-05-12T02:43:06.907+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T02:43:06.909+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:43:06.909+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T02:43:06.924+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:43:06.924+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5
    from airflow_providor.operoter impoer fivetranOperatorAsync
                                   ^
SyntaxError: invalid syntax
[2024-05-12T02:43:06.925+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T02:43:06.943+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.045 seconds
[2024-05-12T02:43:23.091+0000] {processor.py:161} INFO - Started process (PID=272) to work on /opt/airflow/dags/blab.py
[2024-05-12T02:43:23.092+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T02:43:23.095+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:43:23.095+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T02:43:23.114+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:43:23.113+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5
    from airflow_providor_async.operoter impoer fivetranOperatorAsync
                                         ^
SyntaxError: invalid syntax
[2024-05-12T02:43:23.115+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T02:43:23.144+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.067 seconds
[2024-05-12T02:43:44.237+0000] {processor.py:161} INFO - Started process (PID=283) to work on /opt/airflow/dags/blab.py
[2024-05-12T02:43:44.238+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T02:43:44.240+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:43:44.240+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T02:43:44.260+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:43:44.259+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5
    from airflow_provider_async.operoter impoer fivetranOperatorAsync
                                         ^
SyntaxError: invalid syntax
[2024-05-12T02:43:44.261+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T02:43:44.282+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.056 seconds
[2024-05-12T02:44:12.466+0000] {processor.py:161} INFO - Started process (PID=294) to work on /opt/airflow/dags/blab.py
[2024-05-12T02:44:12.468+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T02:44:12.470+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:44:12.470+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T02:44:12.862+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:44:12.857+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5, in <module>
    from airflow_provider_async.operator import fivetranOperatorAsync
ModuleNotFoundError: No module named 'airflow_provider_async'
[2024-05-12T02:44:12.863+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T02:44:12.884+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.426 seconds
[2024-05-12T02:44:31.032+0000] {processor.py:161} INFO - Started process (PID=306) to work on /opt/airflow/dags/blab.py
[2024-05-12T02:44:31.033+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T02:44:31.035+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:44:31.034+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T02:44:31.635+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:44:31.630+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5, in <module>
    from fivetran_provider_async.operator import fivetranOperatorAsync
ModuleNotFoundError: No module named 'fivetran_provider_async'
[2024-05-12T02:44:31.637+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T02:44:31.662+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.637 seconds
[2024-05-12T02:44:51.750+0000] {processor.py:161} INFO - Started process (PID=312) to work on /opt/airflow/dags/blab.py
[2024-05-12T02:44:51.752+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T02:44:51.754+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:44:51.753+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T02:44:52.285+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:44:52.278+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5, in <module>
    from fivetran_provider_async.operators import fivetranOperatorAsync
ModuleNotFoundError: No module named 'fivetran_provider_async'
[2024-05-12T02:44:52.289+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T02:44:52.314+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.571 seconds
[2024-05-12T02:45:22.550+0000] {processor.py:161} INFO - Started process (PID=324) to work on /opt/airflow/dags/blab.py
[2024-05-12T02:45:22.551+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T02:45:22.554+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:45:22.553+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T02:45:23.016+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:45:23.010+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5, in <module>
    from fivetran_provider_async.operators import fivetranOperatorAsync
ModuleNotFoundError: No module named 'fivetran_provider_async'
[2024-05-12T02:45:23.018+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T02:45:23.041+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.499 seconds
[2024-05-12T02:45:53.168+0000] {processor.py:161} INFO - Started process (PID=336) to work on /opt/airflow/dags/blab.py
[2024-05-12T02:45:53.170+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T02:45:53.172+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:45:53.172+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T02:45:53.493+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:45:53.488+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5, in <module>
    from fivetran_provider_async.operators import fivetranOperatorAsync
ModuleNotFoundError: No module named 'fivetran_provider_async'
[2024-05-12T02:45:53.494+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T02:45:53.511+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.352 seconds
[2024-05-12T02:46:23.706+0000] {processor.py:161} INFO - Started process (PID=348) to work on /opt/airflow/dags/blab.py
[2024-05-12T02:46:23.707+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T02:46:23.709+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:46:23.709+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T02:46:24.041+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:46:24.038+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5, in <module>
    from fivetran_provider_async.operators import fivetranOperatorAsync
ModuleNotFoundError: No module named 'fivetran_provider_async'
[2024-05-12T02:46:24.042+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T02:46:24.062+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.363 seconds
[2024-05-12T02:46:54.257+0000] {processor.py:161} INFO - Started process (PID=360) to work on /opt/airflow/dags/blab.py
[2024-05-12T02:46:54.258+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T02:46:54.260+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:46:54.259+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T02:46:54.559+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:46:54.556+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5, in <module>
    from fivetran_provider_async.operators import fivetranOperatorAsync
ModuleNotFoundError: No module named 'fivetran_provider_async'
[2024-05-12T02:46:54.560+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T02:46:54.577+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.327 seconds
[2024-05-12T02:47:24.781+0000] {processor.py:161} INFO - Started process (PID=372) to work on /opt/airflow/dags/blab.py
[2024-05-12T02:47:24.783+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T02:47:24.785+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:47:24.785+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T02:47:25.321+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:47:25.317+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5, in <module>
    from fivetran_provider_async.operators import fivetranOperatorAsync
ModuleNotFoundError: No module named 'fivetran_provider_async'
[2024-05-12T02:47:25.323+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T02:47:25.343+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.570 seconds
[2024-05-12T02:47:55.575+0000] {processor.py:161} INFO - Started process (PID=384) to work on /opt/airflow/dags/blab.py
[2024-05-12T02:47:55.576+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T02:47:55.578+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:47:55.578+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T02:47:56.082+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:47:56.078+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5, in <module>
    from fivetran_provider_async.operators import fivetranOperatorAsync
ModuleNotFoundError: No module named 'fivetran_provider_async'
[2024-05-12T02:47:56.083+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T02:47:56.102+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.538 seconds
[2024-05-12T02:48:26.307+0000] {processor.py:161} INFO - Started process (PID=396) to work on /opt/airflow/dags/blab.py
[2024-05-12T02:48:26.308+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T02:48:26.310+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:48:26.309+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T02:48:26.798+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:48:26.795+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5, in <module>
    from fivetran_provider_async.operators import fivetranOperatorAsync
ModuleNotFoundError: No module named 'fivetran_provider_async'
[2024-05-12T02:48:26.799+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T02:48:26.813+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.513 seconds
[2024-05-12T02:48:57.022+0000] {processor.py:161} INFO - Started process (PID=408) to work on /opt/airflow/dags/blab.py
[2024-05-12T02:48:57.023+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T02:48:57.025+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:48:57.025+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T02:48:57.333+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:48:57.329+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5, in <module>
    from fivetran_provider_async.operators import fivetranOperatorAsync
ModuleNotFoundError: No module named 'fivetran_provider_async'
[2024-05-12T02:48:57.334+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T02:48:57.355+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.340 seconds
[2024-05-12T02:49:27.582+0000] {processor.py:161} INFO - Started process (PID=420) to work on /opt/airflow/dags/blab.py
[2024-05-12T02:49:27.583+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T02:49:27.585+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:49:27.585+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T02:49:27.973+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:49:27.969+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5, in <module>
    from fivetran_provider_async.operators import fivetranOperatorAsync
ModuleNotFoundError: No module named 'fivetran_provider_async'
[2024-05-12T02:49:27.975+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T02:49:28.000+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.427 seconds
[2024-05-12T02:49:58.217+0000] {processor.py:161} INFO - Started process (PID=432) to work on /opt/airflow/dags/blab.py
[2024-05-12T02:49:58.218+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T02:49:58.220+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:49:58.219+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T02:49:58.531+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:49:58.528+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5, in <module>
    from fivetran_provider_async.operators import fivetranOperatorAsync
ModuleNotFoundError: No module named 'fivetran_provider_async'
[2024-05-12T02:49:58.533+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T02:49:58.679+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.469 seconds
[2024-05-12T02:50:11.354+0000] {processor.py:161} INFO - Started process (PID=444) to work on /opt/airflow/dags/blab.py
[2024-05-12T02:50:11.356+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T02:50:11.361+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:50:11.360+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T02:50:11.887+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:50:11.881+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5, in <module>
    from fivetran_provider_async.operators import FivetranOperatorAsync
ModuleNotFoundError: No module named 'fivetran_provider_async'
[2024-05-12T02:50:11.889+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T02:50:11.906+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.562 seconds
[2024-05-12T02:50:41.982+0000] {processor.py:161} INFO - Started process (PID=456) to work on /opt/airflow/dags/blab.py
[2024-05-12T02:50:41.984+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T02:50:41.986+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:50:41.986+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T02:50:42.477+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:50:42.473+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5, in <module>
    from fivetran_provider_async.operators import FivetranOperatorAsync
ModuleNotFoundError: No module named 'fivetran_provider_async'
[2024-05-12T02:50:42.479+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T02:50:42.497+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.522 seconds
[2024-05-12T02:51:12.725+0000] {processor.py:161} INFO - Started process (PID=468) to work on /opt/airflow/dags/blab.py
[2024-05-12T02:51:12.726+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T02:51:12.728+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:51:12.728+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T02:51:13.151+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:51:13.147+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5, in <module>
    from fivetran_provider_async.operators import FivetranOperatorAsync
ModuleNotFoundError: No module named 'fivetran_provider_async'
[2024-05-12T02:51:13.152+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T02:51:13.166+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.447 seconds
[2024-05-12T02:51:43.379+0000] {processor.py:161} INFO - Started process (PID=480) to work on /opt/airflow/dags/blab.py
[2024-05-12T02:51:43.380+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T02:51:43.382+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:51:43.382+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T02:51:43.903+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:51:43.898+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5, in <module>
    from fivetran_provider_async.operators import FivetranOperatorAsync
ModuleNotFoundError: No module named 'fivetran_provider_async'
[2024-05-12T02:51:43.905+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T02:51:43.925+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.553 seconds
[2024-05-12T02:52:14.064+0000] {processor.py:161} INFO - Started process (PID=492) to work on /opt/airflow/dags/blab.py
[2024-05-12T02:52:14.065+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T02:52:14.067+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:52:14.067+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T02:52:14.406+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:52:14.402+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5, in <module>
    from fivetran_provider_async.operators import FivetranOperatorAsync
ModuleNotFoundError: No module named 'fivetran_provider_async'
[2024-05-12T02:52:14.407+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T02:52:14.430+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.374 seconds
[2024-05-12T02:52:44.646+0000] {processor.py:161} INFO - Started process (PID=504) to work on /opt/airflow/dags/blab.py
[2024-05-12T02:52:44.647+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T02:52:44.648+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:52:44.648+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T02:52:45.008+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:52:45.004+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5, in <module>
    from fivetran_provider_async.operators import FivetranOperatorAsync
ModuleNotFoundError: No module named 'fivetran_provider_async'
[2024-05-12T02:52:45.009+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T02:52:45.175+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.536 seconds
[2024-05-12T02:53:15.402+0000] {processor.py:161} INFO - Started process (PID=516) to work on /opt/airflow/dags/blab.py
[2024-05-12T02:53:15.403+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T02:53:15.405+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:53:15.405+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T02:53:15.837+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:53:15.834+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5, in <module>
    from fivetran_provider_async.operators import FivetranOperatorAsync
ModuleNotFoundError: No module named 'fivetran_provider_async'
[2024-05-12T02:53:15.839+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T02:53:15.853+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.460 seconds
[2024-05-12T02:53:45.996+0000] {processor.py:161} INFO - Started process (PID=528) to work on /opt/airflow/dags/blab.py
[2024-05-12T02:53:45.997+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T02:53:45.999+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:53:45.999+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T02:53:46.440+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:53:46.436+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5, in <module>
    from fivetran_provider_async.operators import FivetranOperatorAsync
ModuleNotFoundError: No module named 'fivetran_provider_async'
[2024-05-12T02:53:46.442+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T02:53:46.457+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.469 seconds
[2024-05-12T02:54:16.671+0000] {processor.py:161} INFO - Started process (PID=540) to work on /opt/airflow/dags/blab.py
[2024-05-12T02:54:16.672+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T02:54:16.674+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:54:16.674+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T02:54:17.091+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:54:17.086+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5, in <module>
    from fivetran_provider_async.operators import FivetranOperatorAsync
ModuleNotFoundError: No module named 'fivetran_provider_async'
[2024-05-12T02:54:17.093+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T02:54:17.111+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.446 seconds
[2024-05-12T02:54:47.309+0000] {processor.py:161} INFO - Started process (PID=552) to work on /opt/airflow/dags/blab.py
[2024-05-12T02:54:47.310+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T02:54:47.311+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:54:47.311+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T02:54:47.714+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:54:47.711+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5, in <module>
    from fivetran_provider_async.operators import FivetranOperatorAsync
ModuleNotFoundError: No module named 'fivetran_provider_async'
[2024-05-12T02:54:47.715+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T02:54:47.729+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.427 seconds
[2024-05-12T02:55:18.001+0000] {processor.py:161} INFO - Started process (PID=564) to work on /opt/airflow/dags/blab.py
[2024-05-12T02:55:18.003+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T02:55:18.006+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:55:18.005+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T02:55:18.338+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:55:18.334+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5, in <module>
    from fivetran_provider_async.operators import FivetranOperatorAsync
ModuleNotFoundError: No module named 'fivetran_provider_async'
[2024-05-12T02:55:18.339+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T02:55:18.357+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.369 seconds
[2024-05-12T02:55:48.607+0000] {processor.py:161} INFO - Started process (PID=576) to work on /opt/airflow/dags/blab.py
[2024-05-12T02:55:48.610+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T02:55:48.613+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:55:48.613+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T02:55:49.054+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:55:49.048+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5, in <module>
    from fivetran_provider_async.operators import FivetranOperatorAsync
ModuleNotFoundError: No module named 'fivetran_provider_async'
[2024-05-12T02:55:49.055+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T02:55:49.075+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.484 seconds
[2024-05-12T02:56:19.287+0000] {processor.py:161} INFO - Started process (PID=588) to work on /opt/airflow/dags/blab.py
[2024-05-12T02:56:19.288+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T02:56:19.290+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:56:19.290+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T02:56:19.700+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:56:19.696+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5, in <module>
    from fivetran_provider_async.operators import FivetranOperatorAsync
ModuleNotFoundError: No module named 'fivetran_provider_async'
[2024-05-12T02:56:19.701+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T02:56:19.717+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.437 seconds
[2024-05-12T02:56:49.933+0000] {processor.py:161} INFO - Started process (PID=600) to work on /opt/airflow/dags/blab.py
[2024-05-12T02:56:49.934+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T02:56:49.936+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:56:49.936+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T02:56:50.374+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:56:50.369+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5, in <module>
    from fivetran_provider_async.operators import FivetranOperatorAsync
ModuleNotFoundError: No module named 'fivetran_provider_async'
[2024-05-12T02:56:50.376+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T02:56:50.395+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.469 seconds
[2024-05-12T02:57:20.593+0000] {processor.py:161} INFO - Started process (PID=612) to work on /opt/airflow/dags/blab.py
[2024-05-12T02:57:20.594+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T02:57:20.597+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:57:20.596+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T02:57:21.003+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:57:20.998+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5, in <module>
    from fivetran_provider_async.operators import FivetranOperatorAsync
ModuleNotFoundError: No module named 'fivetran_provider_async'
[2024-05-12T02:57:21.004+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T02:57:21.022+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.436 seconds
[2024-05-12T02:57:51.218+0000] {processor.py:161} INFO - Started process (PID=624) to work on /opt/airflow/dags/blab.py
[2024-05-12T02:57:51.219+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T02:57:51.221+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:57:51.220+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T02:57:51.515+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:57:51.511+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5, in <module>
    from fivetran_provider_async.operators import FivetranOperatorAsync
ModuleNotFoundError: No module named 'fivetran_provider_async'
[2024-05-12T02:57:51.517+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T02:57:51.535+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.324 seconds
[2024-05-12T02:58:21.723+0000] {processor.py:161} INFO - Started process (PID=636) to work on /opt/airflow/dags/blab.py
[2024-05-12T02:58:21.724+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T02:58:21.726+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:58:21.725+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T02:58:22.023+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:58:22.019+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5, in <module>
    from fivetran_provider_async.operators import FivetranOperatorAsync
ModuleNotFoundError: No module named 'fivetran_provider_async'
[2024-05-12T02:58:22.024+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T02:58:22.168+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.452 seconds
[2024-05-12T02:58:52.387+0000] {processor.py:161} INFO - Started process (PID=648) to work on /opt/airflow/dags/blab.py
[2024-05-12T02:58:52.389+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T02:58:52.391+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:58:52.390+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T02:58:52.839+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:58:52.834+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5, in <module>
    from fivetran_provider_async.operators import FivetranOperatorAsync
ModuleNotFoundError: No module named 'fivetran_provider_async'
[2024-05-12T02:58:52.841+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T02:58:52.863+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.484 seconds
[2024-05-12T02:59:23.071+0000] {processor.py:161} INFO - Started process (PID=660) to work on /opt/airflow/dags/blab.py
[2024-05-12T02:59:23.072+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T02:59:23.074+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:59:23.074+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T02:59:23.541+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:59:23.537+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5, in <module>
    from fivetran_provider_async.operators import FivetranOperatorAsync
ModuleNotFoundError: No module named 'fivetran_provider_async'
[2024-05-12T02:59:23.543+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T02:59:23.565+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.500 seconds
[2024-05-12T02:59:53.793+0000] {processor.py:161} INFO - Started process (PID=672) to work on /opt/airflow/dags/blab.py
[2024-05-12T02:59:53.794+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T02:59:53.796+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:59:53.795+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T02:59:54.211+0000] {logging_mixin.py:188} INFO - [2024-05-12T02:59:54.207+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5, in <module>
    from fivetran_provider_async.operators import FivetranOperatorAsync
ModuleNotFoundError: No module named 'fivetran_provider_async'
[2024-05-12T02:59:54.213+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T02:59:54.227+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.440 seconds
[2024-05-12T03:00:24.449+0000] {processor.py:161} INFO - Started process (PID=684) to work on /opt/airflow/dags/blab.py
[2024-05-12T03:00:24.450+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T03:00:24.452+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:00:24.452+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T03:00:24.883+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:00:24.879+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5, in <module>
    from fivetran_provider_async.operators import FivetranOperatorAsync
ModuleNotFoundError: No module named 'fivetran_provider_async'
[2024-05-12T03:00:24.884+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T03:00:24.899+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.457 seconds
[2024-05-12T03:00:55.101+0000] {processor.py:161} INFO - Started process (PID=696) to work on /opt/airflow/dags/blab.py
[2024-05-12T03:00:55.102+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T03:00:55.104+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:00:55.104+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T03:00:55.567+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:00:55.561+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5, in <module>
    from fivetran_provider_async.operators import FivetranOperatorAsync
ModuleNotFoundError: No module named 'fivetran_provider_async'
[2024-05-12T03:00:55.569+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T03:00:55.601+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.507 seconds
[2024-05-12T03:19:49.560+0000] {processor.py:161} INFO - Started process (PID=175) to work on /opt/airflow/dags/blab.py
[2024-05-12T03:19:49.565+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T03:19:49.577+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:19:49.576+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T03:19:56.431+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:19:56.423+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5, in <module>
    from fivetran_provider_async.operators import FivetranOperatorAsync
ImportError: cannot import name 'FivetranOperatorAsync' from 'fivetran_provider_async.operators' (/home/airflow/.local/lib/python3.9/site-packages/fivetran_provider_async/operators.py)
[2024-05-12T03:19:56.435+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T03:19:56.494+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 6.964 seconds
[2024-05-12T03:20:27.248+0000] {processor.py:161} INFO - Started process (PID=187) to work on /opt/airflow/dags/blab.py
[2024-05-12T03:20:27.326+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T03:20:27.339+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:20:27.337+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T03:20:27.962+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:20:27.958+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5, in <module>
    from fivetran_provider_async.operators import FivetranOperatorAsync
ImportError: cannot import name 'FivetranOperatorAsync' from 'fivetran_provider_async.operators' (/home/airflow/.local/lib/python3.9/site-packages/fivetran_provider_async/operators.py)
[2024-05-12T03:20:27.965+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T03:20:28.002+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.763 seconds
[2024-05-12T03:20:58.368+0000] {processor.py:161} INFO - Started process (PID=205) to work on /opt/airflow/dags/blab.py
[2024-05-12T03:20:58.369+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T03:20:58.371+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:20:58.371+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T03:20:58.844+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:20:58.841+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5, in <module>
    from fivetran_provider_async.operators import FivetranOperatorAsync
ImportError: cannot import name 'FivetranOperatorAsync' from 'fivetran_provider_async.operators' (/home/airflow/.local/lib/python3.9/site-packages/fivetran_provider_async/operators.py)
[2024-05-12T03:20:58.845+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T03:20:58.864+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.502 seconds
[2024-05-12T03:21:29.104+0000] {processor.py:161} INFO - Started process (PID=217) to work on /opt/airflow/dags/blab.py
[2024-05-12T03:21:29.106+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T03:21:29.108+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:21:29.107+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T03:21:30.150+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:21:30.145+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5, in <module>
    from fivetran_provider_async.operators import FivetranOperatorAsync
ImportError: cannot import name 'FivetranOperatorAsync' from 'fivetran_provider_async.operators' (/home/airflow/.local/lib/python3.9/site-packages/fivetran_provider_async/operators.py)
[2024-05-12T03:21:30.151+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T03:21:30.198+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 1.102 seconds
[2024-05-12T03:22:01.029+0000] {processor.py:161} INFO - Started process (PID=229) to work on /opt/airflow/dags/blab.py
[2024-05-12T03:22:01.312+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T03:22:01.337+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:22:01.336+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T03:22:04.737+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:22:04.730+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5, in <module>
    from fivetran_provider_async.operators import FivetranOperatorAsync
ImportError: cannot import name 'FivetranOperatorAsync' from 'fivetran_provider_async.operators' (/home/airflow/.local/lib/python3.9/site-packages/fivetran_provider_async/operators.py)
[2024-05-12T03:22:04.739+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T03:22:04.790+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 3.772 seconds
[2024-05-12T03:22:36.311+0000] {processor.py:161} INFO - Started process (PID=241) to work on /opt/airflow/dags/blab.py
[2024-05-12T03:22:36.314+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T03:22:36.320+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:22:36.319+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T03:22:38.170+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:22:38.166+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5, in <module>
    from fivetran_provider_async.operators import FivetranOperatorAsync
ImportError: cannot import name 'FivetranOperatorAsync' from 'fivetran_provider_async.operators' (/home/airflow/.local/lib/python3.9/site-packages/fivetran_provider_async/operators.py)
[2024-05-12T03:22:38.197+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T03:22:38.794+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 2.502 seconds
[2024-05-12T03:23:10.879+0000] {processor.py:161} INFO - Started process (PID=253) to work on /opt/airflow/dags/blab.py
[2024-05-12T03:23:10.887+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T03:23:10.901+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:23:10.899+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T03:23:12.614+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:23:12.599+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5, in <module>
    from fivetran_provider_async.operators import FivetranOperatorAsync
ImportError: cannot import name 'FivetranOperatorAsync' from 'fivetran_provider_async.operators' (/home/airflow/.local/lib/python3.9/site-packages/fivetran_provider_async/operators.py)
[2024-05-12T03:23:12.618+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T03:23:12.721+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 1.864 seconds
[2024-05-12T03:23:44.745+0000] {processor.py:161} INFO - Started process (PID=265) to work on /opt/airflow/dags/blab.py
[2024-05-12T03:23:44.748+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T03:23:44.757+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:23:44.755+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T03:23:46.625+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:23:46.618+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5, in <module>
    from fivetran_provider_async.operators import FivetranOperatorAsync
ImportError: cannot import name 'FivetranOperatorAsync' from 'fivetran_provider_async.operators' (/home/airflow/.local/lib/python3.9/site-packages/fivetran_provider_async/operators.py)
[2024-05-12T03:23:46.627+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T03:23:46.683+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 1.977 seconds
[2024-05-12T03:24:19.798+0000] {processor.py:161} INFO - Started process (PID=277) to work on /opt/airflow/dags/blab.py
[2024-05-12T03:24:19.807+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T03:24:19.856+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:24:19.831+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T03:24:31.374+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:24:31.363+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5, in <module>
    from fivetran_provider_async.operators import FivetranOperatorAsync
ImportError: cannot import name 'FivetranOperatorAsync' from 'fivetran_provider_async.operators' (/home/airflow/.local/lib/python3.9/site-packages/fivetran_provider_async/operators.py)
[2024-05-12T03:24:31.378+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T03:24:31.494+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 11.759 seconds
[2024-05-12T03:25:01.990+0000] {processor.py:161} INFO - Started process (PID=295) to work on /opt/airflow/dags/blab.py
[2024-05-12T03:25:01.992+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T03:25:02.039+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:25:02.038+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T03:25:07.691+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:25:07.686+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5, in <module>
    from fivetran_provider_async.operators import FivetranOperatorAsync
ImportError: cannot import name 'FivetranOperatorAsync' from 'fivetran_provider_async.operators' (/home/airflow/.local/lib/python3.9/site-packages/fivetran_provider_async/operators.py)
[2024-05-12T03:25:07.692+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T03:25:07.725+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 5.845 seconds
[2024-05-12T03:25:38.115+0000] {processor.py:161} INFO - Started process (PID=307) to work on /opt/airflow/dags/blab.py
[2024-05-12T03:25:38.179+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T03:25:38.194+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:25:38.193+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T03:25:39.132+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:25:39.126+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5, in <module>
    from fivetran_provider_async.operators import FivetranOperatorAsync
ImportError: cannot import name 'FivetranOperatorAsync' from 'fivetran_provider_async.operators' (/home/airflow/.local/lib/python3.9/site-packages/fivetran_provider_async/operators.py)
[2024-05-12T03:25:39.134+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T03:25:39.206+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 1.137 seconds
[2024-05-12T03:26:09.539+0000] {processor.py:161} INFO - Started process (PID=319) to work on /opt/airflow/dags/blab.py
[2024-05-12T03:26:09.547+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T03:26:09.557+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:26:09.556+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T03:26:10.471+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:26:10.466+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5, in <module>
    from fivetran_provider_async.operators import FivetranOperatorAsync
ImportError: cannot import name 'FivetranOperatorAsync' from 'fivetran_provider_async.operators' (/home/airflow/.local/lib/python3.9/site-packages/fivetran_provider_async/operators.py)
[2024-05-12T03:26:10.473+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T03:26:10.549+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 1.059 seconds
[2024-05-12T03:26:41.152+0000] {processor.py:161} INFO - Started process (PID=332) to work on /opt/airflow/dags/blab.py
[2024-05-12T03:26:41.160+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T03:26:41.171+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:26:41.169+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T03:26:45.279+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:26:45.264+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5, in <module>
    from fivetran_provider_async.operators import FivetranOperatorAsync
ImportError: cannot import name 'FivetranOperatorAsync' from 'fivetran_provider_async.operators' (/home/airflow/.local/lib/python3.9/site-packages/fivetran_provider_async/operators.py)
[2024-05-12T03:26:45.283+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T03:26:45.386+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 4.274 seconds
[2024-05-12T03:27:16.950+0000] {processor.py:161} INFO - Started process (PID=344) to work on /opt/airflow/dags/blab.py
[2024-05-12T03:27:16.953+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T03:27:17.218+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:27:17.175+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T03:27:22.588+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:27:22.568+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5, in <module>
    from fivetran_provider_async.operators import FivetranOperatorAsync
ImportError: cannot import name 'FivetranOperatorAsync' from 'fivetran_provider_async.operators' (/home/airflow/.local/lib/python3.9/site-packages/fivetran_provider_async/operators.py)
[2024-05-12T03:27:22.598+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T03:27:22.665+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 5.851 seconds
[2024-05-12T03:27:52.767+0000] {processor.py:161} INFO - Started process (PID=356) to work on /opt/airflow/dags/blab.py
[2024-05-12T03:27:52.769+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T03:27:52.772+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:27:52.771+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T03:27:53.273+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:27:53.270+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5, in <module>
    from fivetran_provider_async.operators import FivetranOperatorAsync
ImportError: cannot import name 'FivetranOperatorAsync' from 'fivetran_provider_async.operators' (/home/airflow/.local/lib/python3.9/site-packages/fivetran_provider_async/operators.py)
[2024-05-12T03:27:53.275+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T03:27:53.295+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.538 seconds
[2024-05-12T03:28:23.913+0000] {processor.py:161} INFO - Started process (PID=368) to work on /opt/airflow/dags/blab.py
[2024-05-12T03:28:23.914+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T03:28:23.916+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:28:23.915+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T03:28:24.634+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:28:24.631+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5, in <module>
    from fivetran_provider_async.operators import FivetranOperatorAsync
ImportError: cannot import name 'FivetranOperatorAsync' from 'fivetran_provider_async.operators' (/home/airflow/.local/lib/python3.9/site-packages/fivetran_provider_async/operators.py)
[2024-05-12T03:28:24.635+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T03:28:26.485+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 2.579 seconds
[2024-05-12T03:28:56.737+0000] {processor.py:161} INFO - Started process (PID=380) to work on /opt/airflow/dags/blab.py
[2024-05-12T03:28:56.745+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T03:28:56.763+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:28:56.762+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T03:29:00.823+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:29:00.804+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5, in <module>
    from fivetran_provider_async.operators import FivetranOperatorAsync
ImportError: cannot import name 'FivetranOperatorAsync' from 'fivetran_provider_async.operators' (/home/airflow/.local/lib/python3.9/site-packages/fivetran_provider_async/operators.py)
[2024-05-12T03:29:00.827+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T03:29:00.909+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 4.232 seconds
[2024-05-12T03:29:31.042+0000] {processor.py:161} INFO - Started process (PID=391) to work on /opt/airflow/dags/blab.py
[2024-05-12T03:29:31.046+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T03:29:31.051+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:29:31.050+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T03:29:32.305+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:29:32.298+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 5, in <module>
    from fivetran_provider_async.operators import FivetranOperatorAsync
ImportError: cannot import name 'FivetranOperatorAsync' from 'fivetran_provider_async.operators' (/home/airflow/.local/lib/python3.9/site-packages/fivetran_provider_async/operators.py)
[2024-05-12T03:29:32.310+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T03:29:32.354+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 1.336 seconds
[2024-05-12T03:29:53.534+0000] {processor.py:161} INFO - Started process (PID=403) to work on /opt/airflow/dags/blab.py
[2024-05-12T03:29:53.564+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T03:29:53.629+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:29:53.624+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T03:29:58.721+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:29:58.695+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 65, in <module>
    python_callable=extrect3
NameError: name 'extrect3' is not defined
[2024-05-12T03:29:58.724+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T03:29:59.017+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 5.680 seconds
[2024-05-12T03:30:29.488+0000] {processor.py:161} INFO - Started process (PID=415) to work on /opt/airflow/dags/blab.py
[2024-05-12T03:30:29.489+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T03:30:29.491+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:30:29.491+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T03:30:31.545+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:30:31.540+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 65, in <module>
    python_callable=extrect3
NameError: name 'extrect3' is not defined
[2024-05-12T03:30:31.547+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T03:30:31.823+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 2.386 seconds
[2024-05-12T03:31:02.351+0000] {processor.py:161} INFO - Started process (PID=427) to work on /opt/airflow/dags/blab.py
[2024-05-12T03:31:02.353+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T03:31:02.368+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:31:02.362+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T03:31:04.722+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:31:04.713+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 65, in <module>
    python_callable=extrect3
NameError: name 'extrect3' is not defined
[2024-05-12T03:31:04.725+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T03:31:04.920+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 2.581 seconds
[2024-05-12T03:31:08.432+0000] {processor.py:161} INFO - Started process (PID=433) to work on /opt/airflow/dags/blab.py
[2024-05-12T03:31:08.433+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T03:31:08.436+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:31:08.435+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T03:31:08.834+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T03:31:08.857+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.435 seconds
[2024-05-12T03:31:39.117+0000] {processor.py:161} INFO - Started process (PID=444) to work on /opt/airflow/dags/blab.py
[2024-05-12T03:31:39.118+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T03:31:39.122+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:31:39.122+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T03:31:39.452+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T03:31:39.470+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.360 seconds
[2024-05-12T03:32:09.732+0000] {processor.py:161} INFO - Started process (PID=456) to work on /opt/airflow/dags/blab.py
[2024-05-12T03:32:09.733+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T03:32:09.735+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:32:09.735+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T03:32:10.186+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T03:32:10.203+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.478 seconds
[2024-05-12T03:32:16.300+0000] {processor.py:161} INFO - Started process (PID=468) to work on /opt/airflow/dags/blab.py
[2024-05-12T03:32:16.301+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T03:32:16.302+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:32:16.302+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T03:32:16.319+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:32:16.318+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 6
    from airflow.operators.
                           ^
SyntaxError: invalid syntax
[2024-05-12T03:32:16.320+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T03:32:16.457+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.165 seconds
[2024-05-12T03:32:46.578+0000] {processor.py:161} INFO - Started process (PID=479) to work on /opt/airflow/dags/blab.py
[2024-05-12T03:32:46.580+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T03:32:46.582+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:32:46.581+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T03:32:46.599+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:32:46.598+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 6
    from airflow.operators.
                           ^
SyntaxError: invalid syntax
[2024-05-12T03:32:46.600+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T03:32:46.619+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.048 seconds
[2024-05-12T03:33:16.858+0000] {processor.py:161} INFO - Started process (PID=490) to work on /opt/airflow/dags/blab.py
[2024-05-12T03:33:16.860+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T03:33:16.862+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:33:16.862+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T03:33:16.883+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:33:16.882+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 6
    from airflow.operators.
                           ^
SyntaxError: invalid syntax
[2024-05-12T03:33:16.883+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T03:33:16.901+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.066 seconds
[2024-05-12T03:33:47.138+0000] {processor.py:161} INFO - Started process (PID=501) to work on /opt/airflow/dags/blab.py
[2024-05-12T03:33:47.139+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T03:33:47.141+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:33:47.141+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T03:33:47.159+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:33:47.158+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 6
    from airflow.operators.
                           ^
SyntaxError: invalid syntax
[2024-05-12T03:33:47.159+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T03:33:47.178+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.047 seconds
[2024-05-12T03:34:17.431+0000] {processor.py:161} INFO - Started process (PID=512) to work on /opt/airflow/dags/blab.py
[2024-05-12T03:34:17.432+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T03:34:17.434+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:34:17.433+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T03:34:17.452+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:34:17.450+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 6
    from airflow.operators.
                           ^
SyntaxError: invalid syntax
[2024-05-12T03:34:17.452+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T03:34:17.471+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.046 seconds
[2024-05-12T03:34:29.533+0000] {processor.py:161} INFO - Started process (PID=517) to work on /opt/airflow/dags/blab.py
[2024-05-12T03:34:29.534+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T03:34:29.537+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:34:29.536+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T03:34:29.953+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T03:34:29.971+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.445 seconds
[2024-05-12T03:35:00.283+0000] {processor.py:161} INFO - Started process (PID=529) to work on /opt/airflow/dags/blab.py
[2024-05-12T03:35:00.285+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T03:35:00.288+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:35:00.287+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T03:35:00.577+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T03:35:00.590+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.318 seconds
[2024-05-12T03:35:11.370+0000] {processor.py:161} INFO - Started process (PID=535) to work on /opt/airflow/dags/blab.py
[2024-05-12T03:35:11.371+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T03:35:11.373+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:35:11.373+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T03:35:11.401+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T03:35:11.415+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.052 seconds
[2024-05-12T03:35:41.635+0000] {processor.py:161} INFO - Started process (PID=546) to work on /opt/airflow/dags/blab.py
[2024-05-12T03:35:41.636+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T03:35:41.637+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:35:41.637+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T03:35:41.656+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T03:35:41.669+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.040 seconds
[2024-05-12T03:36:11.929+0000] {processor.py:161} INFO - Started process (PID=557) to work on /opt/airflow/dags/blab.py
[2024-05-12T03:36:11.930+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T03:36:11.932+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:36:11.932+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T03:36:11.951+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T03:36:11.966+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.045 seconds
[2024-05-12T03:36:42.242+0000] {processor.py:161} INFO - Started process (PID=568) to work on /opt/airflow/dags/blab.py
[2024-05-12T03:36:42.243+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T03:36:42.245+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:36:42.245+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T03:36:42.262+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T03:36:42.274+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.038 seconds
[2024-05-12T03:37:12.622+0000] {processor.py:161} INFO - Started process (PID=579) to work on /opt/airflow/dags/blab.py
[2024-05-12T03:37:12.623+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T03:37:12.625+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:37:12.625+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T03:37:12.647+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T03:37:12.663+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.049 seconds
[2024-05-12T03:37:42.953+0000] {processor.py:161} INFO - Started process (PID=591) to work on /opt/airflow/dags/blab.py
[2024-05-12T03:37:42.954+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T03:37:42.956+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:37:42.955+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T03:37:42.974+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T03:37:42.986+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.040 seconds
[2024-05-12T03:38:13.199+0000] {processor.py:161} INFO - Started process (PID=602) to work on /opt/airflow/dags/blab.py
[2024-05-12T03:38:13.200+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T03:38:13.202+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:38:13.202+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T03:38:13.220+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T03:38:13.237+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.044 seconds
[2024-05-12T03:38:43.507+0000] {processor.py:161} INFO - Started process (PID=613) to work on /opt/airflow/dags/blab.py
[2024-05-12T03:38:43.508+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T03:38:43.510+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:38:43.510+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T03:38:43.531+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T03:38:43.544+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.045 seconds
[2024-05-12T03:39:13.805+0000] {processor.py:161} INFO - Started process (PID=624) to work on /opt/airflow/dags/blab.py
[2024-05-12T03:39:13.806+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T03:39:13.808+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:39:13.808+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T03:39:13.826+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T03:39:13.839+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.040 seconds
[2024-05-12T03:39:44.129+0000] {processor.py:161} INFO - Started process (PID=635) to work on /opt/airflow/dags/blab.py
[2024-05-12T03:39:44.130+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T03:39:44.132+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:39:44.132+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T03:39:44.154+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T03:39:44.167+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.044 seconds
[2024-05-12T03:40:14.439+0000] {processor.py:161} INFO - Started process (PID=646) to work on /opt/airflow/dags/blab.py
[2024-05-12T03:40:14.441+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T03:40:14.444+0000] {logging_mixin.py:188} INFO - [2024-05-12T03:40:14.444+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T03:40:14.466+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T03:40:14.478+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.049 seconds
[2024-05-12T10:36:51.503+0000] {processor.py:161} INFO - Started process (PID=174) to work on /opt/airflow/dags/blab.py
[2024-05-12T10:36:51.510+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T10:36:51.539+0000] {logging_mixin.py:188} INFO - [2024-05-12T10:36:51.536+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T10:36:51.632+0000] {logging_mixin.py:188} INFO - [2024-05-12T10:36:51.613+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 40
    connector_id="",
    ^
SyntaxError: invalid syntax
[2024-05-12T10:36:51.636+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T10:36:51.742+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.284 seconds
[2024-05-12T10:37:22.156+0000] {processor.py:161} INFO - Started process (PID=186) to work on /opt/airflow/dags/blab.py
[2024-05-12T10:37:22.161+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T10:37:22.177+0000] {logging_mixin.py:188} INFO - [2024-05-12T10:37:22.175+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T10:37:22.224+0000] {logging_mixin.py:188} INFO - [2024-05-12T10:37:22.221+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 40
    connector_id="",
    ^
SyntaxError: invalid syntax
[2024-05-12T10:37:22.225+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T10:37:22.379+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.284 seconds
[2024-05-12T10:37:53.224+0000] {processor.py:161} INFO - Started process (PID=197) to work on /opt/airflow/dags/blab.py
[2024-05-12T10:37:53.227+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T10:37:53.229+0000] {logging_mixin.py:188} INFO - [2024-05-12T10:37:53.229+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T10:37:53.292+0000] {logging_mixin.py:188} INFO - [2024-05-12T10:37:53.291+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 40
    connector_id="",
    ^
SyntaxError: invalid syntax
[2024-05-12T10:37:53.292+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T10:37:53.342+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.131 seconds
[2024-05-12T10:38:24.645+0000] {processor.py:161} INFO - Started process (PID=208) to work on /opt/airflow/dags/blab.py
[2024-05-12T10:38:25.444+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T10:38:25.447+0000] {logging_mixin.py:188} INFO - [2024-05-12T10:38:25.446+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T10:38:25.545+0000] {logging_mixin.py:188} INFO - [2024-05-12T10:38:25.544+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 40
    connector_id="",
    ^
SyntaxError: invalid syntax
[2024-05-12T10:38:25.546+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T10:38:26.991+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 2.351 seconds
[2024-05-12T10:38:58.974+0000] {processor.py:161} INFO - Started process (PID=219) to work on /opt/airflow/dags/blab.py
[2024-05-12T10:38:58.975+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T10:38:58.977+0000] {logging_mixin.py:188} INFO - [2024-05-12T10:38:58.977+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T10:38:59.241+0000] {logging_mixin.py:188} INFO - [2024-05-12T10:38:59.240+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 40
    connector_id="",
    ^
SyntaxError: invalid syntax
[2024-05-12T10:38:59.241+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T10:38:59.509+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.548 seconds
[2024-05-12T10:39:29.832+0000] {processor.py:161} INFO - Started process (PID=230) to work on /opt/airflow/dags/blab.py
[2024-05-12T10:39:29.837+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T10:39:29.847+0000] {logging_mixin.py:188} INFO - [2024-05-12T10:39:29.844+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T10:39:29.875+0000] {logging_mixin.py:188} INFO - [2024-05-12T10:39:29.873+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 40
    connector_id="",
    ^
SyntaxError: invalid syntax
[2024-05-12T10:39:29.876+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T10:39:29.940+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.147 seconds
[2024-05-12T10:40:01.203+0000] {processor.py:161} INFO - Started process (PID=242) to work on /opt/airflow/dags/blab.py
[2024-05-12T10:40:01.227+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T10:40:01.337+0000] {logging_mixin.py:188} INFO - [2024-05-12T10:40:01.333+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T10:40:01.509+0000] {logging_mixin.py:188} INFO - [2024-05-12T10:40:01.496+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 40
    connector_id="",
    ^
SyntaxError: invalid syntax
[2024-05-12T10:40:01.513+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T10:40:01.936+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.797 seconds
[2024-05-12T10:40:21.038+0000] {processor.py:161} INFO - Started process (PID=253) to work on /opt/airflow/dags/blab.py
[2024-05-12T10:40:21.047+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T10:40:21.051+0000] {logging_mixin.py:188} INFO - [2024-05-12T10:40:21.051+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T10:40:21.167+0000] {logging_mixin.py:188} INFO - [2024-05-12T10:40:21.165+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 40
    connector_id="as",
    ^
SyntaxError: invalid syntax
[2024-05-12T10:40:21.168+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T10:40:21.259+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.261 seconds
[2024-05-12T10:40:52.501+0000] {processor.py:161} INFO - Started process (PID=264) to work on /opt/airflow/dags/blab.py
[2024-05-12T10:40:52.523+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T10:40:52.559+0000] {logging_mixin.py:188} INFO - [2024-05-12T10:40:52.555+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T10:40:52.649+0000] {logging_mixin.py:188} INFO - [2024-05-12T10:40:52.640+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 40
    connector_id="as",
    ^
SyntaxError: invalid syntax
[2024-05-12T10:40:52.652+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T10:40:52.904+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.510 seconds
[2024-05-12T10:41:18.691+0000] {processor.py:161} INFO - Started process (PID=275) to work on /opt/airflow/dags/blab.py
[2024-05-12T10:41:18.765+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T10:41:18.991+0000] {logging_mixin.py:188} INFO - [2024-05-12T10:41:18.960+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T10:41:19.324+0000] {logging_mixin.py:188} INFO - [2024-05-12T10:41:19.280+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 40
    connector_id="as",
    ^
SyntaxError: invalid syntax
[2024-05-12T10:41:19.336+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T10:41:20.421+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 2.616 seconds
[2024-05-12T10:41:52.217+0000] {processor.py:161} INFO - Started process (PID=286) to work on /opt/airflow/dags/blab.py
[2024-05-12T10:41:52.233+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T10:41:52.275+0000] {logging_mixin.py:188} INFO - [2024-05-12T10:41:52.264+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T10:41:52.342+0000] {logging_mixin.py:188} INFO - [2024-05-12T10:41:52.334+0000] {dagbag.py:350} ERROR - Failed to import: /opt/airflow/dags/blab.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/models/dagbag.py", line 346, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 846, in exec_module
  File "<frozen importlib._bootstrap_external>", line 983, in get_code
  File "<frozen importlib._bootstrap_external>", line 913, in source_to_code
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/opt/airflow/dags/blab.py", line 40
    connector_id="as",
    ^
SyntaxError: invalid syntax
[2024-05-12T10:41:52.344+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T10:41:52.583+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.731 seconds
[2024-05-12T10:42:24.473+0000] {processor.py:161} INFO - Started process (PID=298) to work on /opt/airflow/dags/blab.py
[2024-05-12T10:42:24.490+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T10:42:24.678+0000] {logging_mixin.py:188} INFO - [2024-05-12T10:42:24.580+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T10:42:24.771+0000] {logging_mixin.py:188} INFO - [2024-05-12T10:42:24.770+0000] {dagbag.py:329} INFO - File /opt/airflow/dags/blab.py assumed to contain no DAGs. Skipping.
[2024-05-12T10:42:24.781+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T10:42:25.177+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.854 seconds
[2024-05-12T10:42:55.960+0000] {processor.py:161} INFO - Started process (PID=309) to work on /opt/airflow/dags/blab.py
[2024-05-12T10:42:55.969+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T10:42:56.013+0000] {logging_mixin.py:188} INFO - [2024-05-12T10:42:56.009+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T10:42:56.053+0000] {logging_mixin.py:188} INFO - [2024-05-12T10:42:56.053+0000] {dagbag.py:329} INFO - File /opt/airflow/dags/blab.py assumed to contain no DAGs. Skipping.
[2024-05-12T10:42:56.056+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T10:42:56.361+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.568 seconds
[2024-05-12T10:43:29.935+0000] {processor.py:161} INFO - Started process (PID=320) to work on /opt/airflow/dags/blab.py
[2024-05-12T10:43:29.960+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T10:43:29.988+0000] {logging_mixin.py:188} INFO - [2024-05-12T10:43:29.986+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T10:43:30.029+0000] {logging_mixin.py:188} INFO - [2024-05-12T10:43:30.029+0000] {dagbag.py:329} INFO - File /opt/airflow/dags/blab.py assumed to contain no DAGs. Skipping.
[2024-05-12T10:43:30.031+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T10:43:30.220+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 2.823 seconds
[2024-05-12T10:44:02.265+0000] {processor.py:161} INFO - Started process (PID=331) to work on /opt/airflow/dags/blab.py
[2024-05-12T10:44:02.282+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T10:44:02.318+0000] {logging_mixin.py:188} INFO - [2024-05-12T10:44:02.315+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T10:44:02.338+0000] {logging_mixin.py:188} INFO - [2024-05-12T10:44:02.338+0000] {dagbag.py:329} INFO - File /opt/airflow/dags/blab.py assumed to contain no DAGs. Skipping.
[2024-05-12T10:44:02.340+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T10:44:02.568+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.496 seconds
[2024-05-12T10:44:32.963+0000] {processor.py:161} INFO - Started process (PID=342) to work on /opt/airflow/dags/blab.py
[2024-05-12T10:44:32.972+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T10:44:32.978+0000] {logging_mixin.py:188} INFO - [2024-05-12T10:44:32.977+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T10:44:33.005+0000] {logging_mixin.py:188} INFO - [2024-05-12T10:44:33.004+0000] {dagbag.py:329} INFO - File /opt/airflow/dags/blab.py assumed to contain no DAGs. Skipping.
[2024-05-12T10:44:33.012+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T10:44:33.112+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.209 seconds
[2024-05-12T10:45:04.421+0000] {processor.py:161} INFO - Started process (PID=353) to work on /opt/airflow/dags/blab.py
[2024-05-12T10:45:04.424+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/blab.py for tasks to queue
[2024-05-12T10:45:04.428+0000] {logging_mixin.py:188} INFO - [2024-05-12T10:45:04.427+0000] {dagbag.py:540} INFO - Filling up the DagBag from /opt/airflow/dags/blab.py
[2024-05-12T10:45:04.439+0000] {logging_mixin.py:188} INFO - [2024-05-12T10:45:04.439+0000] {dagbag.py:329} INFO - File /opt/airflow/dags/blab.py assumed to contain no DAGs. Skipping.
[2024-05-12T10:45:04.440+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/blab.py
[2024-05-12T10:45:05.085+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/blab.py took 0.749 seconds
